prng_key: 14141
loss_config:
  p : 2
  nr_acf_lags: 35
  use_acf_directly: True
  num_KL_samples: 5000
  use_kl_div: True
learn_config:
  learn_acf: False
  learn_marginal: True
  learn_both: False
trawl_config:
  tau: 1.0
  seq_len: 1500
  theta_size: 5
  batch_size: 64
  marginal_distr: NIG
  acf: sup_IG
  trawl_process_type: sup_ig_nig_5p
  acf_prior_hyperparams:
    distr_name: uniform
    gamma_prior_hyperparams: [10.,20.]
    eta_prior_hyperparams: [10.,20.]   
  marginal_distr_hyperparams:
    distr_name: uniform 
    loc_prior_hyperparams: [-1.,1.]
    scale_prior_hyperparams: [0.5,1.5]
    beta_prior_hyperparams: [-5.,5.] 
model_config:
    model_name: LSTMModel
    lstm_hidden_size: 64
    num_lstm_layers: 2
    linear_layer_sizes: [32,24,16,8,4]
    mean_aggregation: True
    final_output_size: 3
    dropout_rate: 0.15 
    with_theta: False
    experiment_dir: summary_statistics
    experiment_subdir: exp_1
train_config:
  n_iterations: 9001
val_config:
  val_freq: 400
  val_n_batches: 42
optimizer:
  name: adam
  lr: 0.0001
  weight_decay: 0.0001