prng_key: 3133
loss_config:
  p : 2
  nr_acf_lags: 35
  use_acf_directly: True
  num_KL_samples: 5000
  use_kl_div: True
learn_config:
  learn_acf: True
  learn_marginal: False
  learn_both: False
trawl_config:
  tau: 1.0
  seq_len: 1500
  theta_size: 5
  batch_size: 64
  marginal_distr: NIG
  acf: sup_IG
  trawl_process_type: sup_ig_nig_5p
  acf_prior_hyperparams:
    distr_name: uniform
    gamma_prior_hyperparams: [10.,20.]
    eta_prior_hyperparams: [10.,20.]   
  marginal_distr_hyperparams:
    distr_name: uniform 
    loc_prior_hyperparams: [-1.,1.]
    scale_prior_hyperparams: [0.5,1.5]
    beta_prior_hyperparams: [-5.,5.] 
model_config:
    model_name: CNN
    max_lag: 35
    conv_channels: [16,32,16]
    fc_sizes: [16,8,4]
    final_output_size: 3
    conv_kernels: [15,5]
    dropout_rate: 0.1
    with_theta: False
train_config:
  n_iterations: 15001 
val_config:
  val_freq: 500
  val_n_batches: 40
optimizer:
  name: adam
  lr: 0.0003
  weight_decay: 0.00001