prng_key: 237
trawl_config:
  tau: 1.0
  seq_len: 1000
  theta_size: 5
  batch_size: 64
  marginal_distr: NIG
  acf: sup_IG
  trawl_type: sup_ig_nig_5p
  acf_prior_hyperparams:
    distr_name: uniform
    gamma_prior_hyperparams: [10.,20.]
    eta_prior_hyperparams: [10.,20.]   
  marginal_distr_hyperparams:
    distr_name: uniform 
    loc_prior_hyperparams: [-1.,1.]
    scale_prior_hyperparams: [0.5,1.5]
    beta_prior_hyperparams: [-5.,5.] 
model_config:
    model_name: LSTMModel
    lstm_hidden_size: 64
    num_lstm_layers: 2
    linear_layer_sizes: [32,16,8]
    mean_aggregation: False
    final_output_size: 5
    with_theta: False
    experiment_dir: summary_statistics
    experiment_subdir: exp_1
train_config:
  n_iterations: 5000 
  n_acc_steps_per_iterations: 10
  batch_size: 64
val_config:
  val_freq: 10
  val_n_batches: 100
  val_batch_size: 128
optimizer:
  name: adam
  lr: 0.0001