prng_key: 1424
loss_config:
  p : 2
  nr_acf_lags: 35
  use_acf_directly: True
  num_KL_samples: 5000
  use_kl_div: True
learn_config:
  learn_acf: True
  learn_marginal: False
  learn_both: False
trawl_config:
  tau: 1.0
  seq_len: 1500
  theta_size: 5
  batch_size: 64
  marginal_distr: NIG
  acf: sup_IG
  trawl_process_type: sup_ig_nig_5p
  acf_prior_hyperparams:
    distr_name: uniform
    gamma_prior_hyperparams: [10.,20.]
    eta_prior_hyperparams: [10.,20.]   
  marginal_distr_hyperparams:
    distr_name: uniform 
    loc_prior_hyperparams: [-1.,1.]
    scale_prior_hyperparams: [0.5,1.5]
    beta_prior_hyperparams: [-5.,5.] 
model_config:
    model_name: LSTMModel
    lstm_hidden_size: 32
    num_lstm_layers: 1
    linear_layer_sizes: [16,8,4]
    mean_aggregation: False
    final_output_size: 2
    dropout_rate: 0.105
    with_theta: False
    experiment_dir: summary_statistics
    experiment_subdir: exp_1
train_config:
  n_iterations: 6001 
val_config:
  val_freq: 300
  val_n_batches: 40
optimizer:
  name: adam
  lr: 0.0003
  weight_decay: 0.0001