prng_key: 212111
tre_config:
  use_tre: True
  tre_type: beta 
  use_summary_statistics: True
  replace_full_trawl_with_acf: False
  nlags: 35
trawl_config:
  tau: 1.0
  seq_len: 1500
  input_size: 5
  theta_size: 5
  batch_size: 128
  marginal_distr: NIG
  acf: sup_IG
  trawl_process_type: sup_ig_nig_5p
  acf_prior_hyperparams:
    distr_name: uniform
    gamma_prior_hyperparams: [10.,20.]
    eta_prior_hyperparams: [10.,20.]   
  marginal_distr_hyperparams:
    distr_name: uniform 
    loc_prior_hyperparams: [-1.,1.]
    scale_prior_hyperparams: [0.5,1.5]
    beta_prior_hyperparams: [-5.,5.] 
model_config:
    model_name: DenseModel
    linear_layer_sizes: [32,16,8,4]
    final_output_size: 1
    dropout_rate: 0.1
    with_theta: True
train_config:
  n_iterations: 50001 
val_config:
  val_freq: 300
  val_n_batches: 40
optimizer:
  name: adam
  lr: 0.001
  weight_decay: 0.0001
  alpha: 0.005