learn_config:
  learn_acf: false
  learn_both: false
  learn_marginal: true
model_config:
  experiment_dir: summary_statistics
  final_output_size: 3
  linear_layer_sizes:
  - 32
  - 16
  - 8
  - 4
  lstm_hidden_size: 64
  mean_aggregation: false
  model_name: LSTMModel
  num_lstm_layers: 2
  with_theta: false
optimizer:
  lr: 0.001
  name: adam
prng_key: 141421
train_config:
  batch_size: 64
  n_iterations: 1001
trawl_config:
  acf: sup_IG
  acf_prior_hyperparams:
    distr_name: uniform
    eta_prior_hyperparams:
    - 10.0
    - 20.0
    gamma_prior_hyperparams:
    - 10.0
    - 20.0
  batch_size: 64
  marginal_distr: NIG
  marginal_distr_hyperparams:
    beta_prior_hyperparams:
    - -5.0
    - 5.0
    distr_name: uniform
    loc_prior_hyperparams:
    - -1.0
    - 1.0
    scale_prior_hyperparams:
    - 0.5
    - 1.5
  seq_len: 1500
  tau: 1.0
  theta_size: 5
  trawl_type: sup_ig_nig_5p
val_config:
  val_freq: 100
  val_n_batches: 50
